[package]
name = "cowardcoin"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
bincode = "2.0.1"
dotenv = "0.15.0"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
